name: 'Pullquote'
description: 'Update pullquotes in documentation'
runs:
  using: 'docker'
  image: 'action.Dockerfile'
inputs:
  walk:
    description: 'Whether to automatically discover documentation.'
    required: false
    default: 'true'
  check:
    description: 'Whether to exit with an error code if not up-to-date'
    required: false
    default: 'false'
  files:
    description: 'Whitespace-delimited list of files to operate on'
    required: false
    default: ''
