on: [push]

jobs:
  pullquote:
    runs-on: ubuntu-latest
    name: Update any pullquotes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pullquote
        uses: jwilner/pullquote@action
